package com.example.gui;

import com.example.data.Animal;
import com.example.data.HistoriaClinica;
import com.example.data.Usuarios;
import java.util.Calendar;
import com.example.gui.RegistrarAnimal;
import com.example.gui.GestionarUsuarios;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class GestionarHistoriaClinica extends javax.swing.JFrame {

    RegistrarAnimal regAnimales = new RegistrarAnimal();
    GestionarUsuarios regUsuarios = new GestionarUsuarios();
    ArrayList<HistoriaClinica> listaHistoria = new ArrayList<>();

    int conse = 1;

    public GestionarHistoriaClinica() {
        initComponents();

        Calendar hoy = Calendar.getInstance();
        int d = hoy.get(Calendar.DAY_OF_MONTH);
        int m = hoy.get(Calendar.MONTH+1);
        int a = hoy.get(Calendar.YEAR);

        String fecha = d + "/" + m + "/" + a;
        Fecha.setText(fecha);

        CargarDatosAnimales();
        CargarDatosUsuarios();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SeleccionAnimal = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        procedimiento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        SeleccionUsuario = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        consecutivo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("GESTIONAR HISTORIA CLINICA");

        jLabel2.setText("Fecha");

        Fecha.setFocusable(false);

        jLabel3.setText("Consecutivo");

        jLabel4.setText("Animal");

        SeleccionAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un animal" }));
        SeleccionAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionAnimalActionPerformed(evt);
            }
        });

        jLabel5.setText("Procedimiento a Realizar");

        procedimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Procedimiento", "Parto", "Vacunación", "Control por Crecimiento" }));
        procedimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procedimientoActionPerformed(evt);
            }
        });

        jLabel6.setText("Usuario");

        SeleccionUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Usuario" }));
        SeleccionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionUsuarioActionPerformed(evt);
            }
        });

        jLabel7.setText("Observaciones");

        observaciones.setColumns(20);
        observaciones.setRows(5);
        jScrollPane1.setViewportView(observaciones);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        consecutivo.setText("1");
        consecutivo.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(SeleccionUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(procedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(SeleccionAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consecutivo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fecha))
                    .addComponent(jLabel1))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Fecha))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(consecutivo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SeleccionAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(procedimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SeleccionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void CargarDatosAnimales() {
        ArrayList<Animal> registro = regAnimales.getListaAnimales();
        for (Animal regis : registro) {
            SeleccionAnimal.addItem(regis.getCodigo() + regis.getNombre());
        }
    }

    public void CargarDatosUsuarios() {
        ArrayList<Usuarios> registroUsuarios = regUsuarios.getListaUsuarios();
        for (Usuarios reg : registroUsuarios) {
            SeleccionUsuario.addItem(reg.getNombres() + " " + reg.getDocumento());
        }
    }

    private void SeleccionAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionAnimalActionPerformed

    }//GEN-LAST:event_SeleccionAnimalActionPerformed

    private void SeleccionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionUsuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        HistoriaClinica historia = new HistoriaClinica();
        historia.setFecha(Fecha.getText());
        historia.setConsecutivo(consecutivo.getText());
        
        if (SeleccionAnimal.getSelectedItem().equals("Seleccione un animal")){
            JOptionPane.showMessageDialog(null, "Escoja una opcion valida", "Animal no seleccionado", JOptionPane.WARNING_MESSAGE);
               
        }else if(procedimiento.getSelectedItem().equals("Seleccione un Procedimiento")){
            JOptionPane.showMessageDialog(null, "Escoja una opcion valida", "Procedimiento no seleccionado", JOptionPane.WARNING_MESSAGE);
        
        }else if(SeleccionUsuario.getSelectedItem().equals("Seleccione un Usuario")){
            JOptionPane.showMessageDialog(null, "Escoja una opcion valida", "Usuario no seleccionado", JOptionPane.WARNING_MESSAGE);
        }else{
            
        
        historia.setAnimal(SeleccionAnimal.getSelectedItem().toString());
        historia.setProcedimiento(procedimiento.getSelectedItem().toString());
        historia.setUsuario(SeleccionUsuario.getSelectedItem().toString());
        historia.setObservaciones(observaciones.getText());
        listaHistoria.add(historia);
        conse = conse + 1;
        consecutivo.setText(Integer.toString(conse));
        JOptionPane.showMessageDialog(null, "Novedad agregada Exitosamente");
        
        SeleccionAnimal.setSelectedIndex(0);
        procedimiento.setSelectedIndex(0);
        SeleccionUsuario.setSelectedIndex(0);
        observaciones.setText("");
        }
        System.out.println(historia);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void procedimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procedimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procedimientoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarHistoriaClinica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fecha;
    private javax.swing.JComboBox<String> SeleccionAnimal;
    private javax.swing.JComboBox<String> SeleccionUsuario;
    private javax.swing.JLabel consecutivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea observaciones;
    private javax.swing.JComboBox<String> procedimiento;
    // End of variables declaration//GEN-END:variables
}
