package com.example.gui;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import com.example.data.Animal;
import javax.swing.JOptionPane;
import javax.swing.text.html.FormView;

public class RegistrarAnimal extends javax.swing.JFrame {

    static ArrayList<Animal> ListaAnimales = new ArrayList<Animal>();

    public ArrayList<Animal> getListaAnimales() {
        return ListaAnimales;
    }

    public RegistrarAnimal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigoAnimal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        categoriaAnimal = new javax.swing.JComboBox<>();
        razaAnimal = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreAnimal = new javax.swing.JTextField();
        botonRegresarAnimal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Codigo");

        jLabel2.setText("Categoria");

        categoriaAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la Categoria...", "Bovino", "Porcino", "Equino" }));
        categoriaAnimal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                categoriaAnimalItemStateChanged(evt);
            }
        });
        categoriaAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaAnimalActionPerformed(evt);
            }
        });

        razaAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Raza" }));
        razaAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                razaAnimalActionPerformed(evt);
            }
        });

        jLabel3.setText("Raza");

        jLabel4.setText("Nombre");

        nombreAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreAnimalActionPerformed(evt);
            }
        });

        botonRegresarAnimal.setText("Regresar");
        botonRegresarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarAnimalActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("REGISTRAR ANIMAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(codigoAnimal)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(razaAnimal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoriaAnimal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(botonRegresarAnimal)
                                .addGap(63, 63, 63)
                                .addComponent(jButton1)))
                        .addGap(112, 112, 112))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(categoriaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(razaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(nombreAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegresarAnimal)
                    .addComponent(jButton1))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreAnimalActionPerformed

    private void botonRegresarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarAnimalActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonRegresarAnimalActionPerformed

    private void razaAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_razaAnimalActionPerformed


    }//GEN-LAST:event_razaAnimalActionPerformed

    private void categoriaAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaAnimalActionPerformed

    }//GEN-LAST:event_categoriaAnimalActionPerformed

    private void categoriaAnimalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_categoriaAnimalItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.categoriaAnimal.getSelectedIndex() > 0) {
                this.razaAnimal.setModel(new DefaultComboBoxModel(this.getRazas(this.categoriaAnimal.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_categoriaAnimalItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Animal animal = new Animal();

        

        if (nombreAnimal.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Introduzca un nombre", "Nombre incorrecto", JOptionPane.ERROR_MESSAGE);
        
        } else if (codigoAnimal.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Introduzca un codigo valido", "Codigo incorrecto", JOptionPane.ERROR_MESSAGE);
        
        }else if (categoriaAnimal.getSelectedItem().equals("Seleccione la Categoria...")){
            JOptionPane.showMessageDialog(null, "Escoja una categoria", "Categoria vacia", JOptionPane.INFORMATION_MESSAGE);
            
        
        } else {
            animal.setCategoria(categoriaAnimal.getSelectedItem().toString());
            animal.setRaza(razaAnimal.getSelectedItem().toString());
            animal.setCodigo(codigoAnimal.getText());
            animal.setNombre(nombreAnimal.getText());
            ListaAnimales.add(animal);
            JOptionPane.showMessageDialog(null, "Animal registrado exitosamente");

            codigoAnimal.setText("");
            categoriaAnimal.setSelectedIndex(0);
            nombreAnimal.setText("");
            System.out.println(ListaAnimales);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public String[] getRazas(String Razas) {
        String[] razas = new String[4];
        
        
        
        
        if (categoriaAnimal.getSelectedItem().equals("Bovino")) {
            razas[0] = "Blanco oreginegro";
            razas[1] = "Chino santandereano";
            razas[2] = "Costeño con cuernos";
            razas[3] = "Hartón del valle";
        }
        if (categoriaAnimal.getSelectedItem().equals("Porcino")) {
            razas[0] = "Duroc Jersey";
            razas[1] = "Pietrán";
            razas[2] = "Landra";
            razas[3] = "Yorkshire";
        }
        if (categoriaAnimal.getSelectedItem().equals("Equino")) {
            razas[0] = "Pura sangre";
            razas[1] = "Andalucía";
            razas[2] = "Percherón";
        }
        return razas;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarAnimal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresarAnimal;
    private javax.swing.JComboBox<String> categoriaAnimal;
    private javax.swing.JTextField codigoAnimal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreAnimal;
    private javax.swing.JComboBox<String> razaAnimal;
    // End of variables declaration//GEN-END:variables

}
